[package]
name = "unbound"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctor = "0.2.8"
unbound-sys = { path = "../unbound-sys" }
